version: "3"
services:
    node-app:
        container_name: node-app-dev
        volumes: 
            - ./:/app
            - /app/node_modules
        environment: 
            - NODE_ENV=development
        command: npm run dev