version: "3"
services:
  node-app:
    container_name: node-app-prod
    hostname: node-app-prod
    build:
      context: .
      args:
        NODE_ENV: production
    ports:
      - "4000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    command: node index.js
