version: "3"
services:
  node-app:
    container_name: node-app-prod
    build:
      context: .
      args: 
        NODE_ENV: production
    environment:
      - NODE_ENV=production
    command: node index.js
