version: "3"

volumes:
  portainer_data:

services:
  node-app:
    container_name: node-app-dev
    hostname: node-app-dev
    build:
      context: .
      args:
        NODE_ENV: development
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=3000
    command: npm run dev

  portainer:
    container_name: portainer
    hostname: portainer
    image: portainer/portainer-ce
    ports:
      - "9000:9000"
    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
